### ISSUE TITLE
Warnings during installation

### ISSUE THREAD

**Issue by OElesin** [stormpython/vectormap#3]
I got this error while installing this plugin on Kibana 4.5.0
`[BABEL] Note: The code generator has deoptimised the styling of "/sw/elk/kibana/installedPlugins/vectormap/public/lib/jvectormap/maps/map.asia_mill.js" as it exceeds the max of "100KB".
[BABEL] Note: The code generator has deoptimised the styling of "/sw/elk/kibana/installedPlugins/vectormap/public/lib/jvectormap/maps/map.europe_mill.js" as it exceeds the max of "100KB".
[BABEL] Note: The code generator has deoptimised the styling of "/sw/elk/kibana/installedPlugins/vectormap/public/lib/jvectormap/maps/map.world_mill.js" as it exceeds the max of "100KB"`

Does this mean this features will not be available? or is there a fix for this?

**Comment by stormpython** [comment]
No. It simply means that some of the map files are too big to be minified. It shouldn't affect the behavior of the visualization.
