### ISSUE TITLE
Cannot find the plugin after installation

### ISSUE THREAD

**Issue by ThorstenBux** [stormpython/vectormap#4]
Hi,

I'm new to Kibana and installing plugins. I followed the readme.md for installing this plugin and installed it like this:
./kibana plugin -i vectormap -u https://github.com/stormpython/vectormap/archive/master.zip

while the shell was already in the bin directory of kibana.
The Installation went well however I cannot find the plugin inside the Kibana UI. 

Do I need to do some additional configuration?

Thanks for your help

Using Kibana:
Version 	4.5.0
Build 	9889

On Ubuntu Linux 14.04

**Comment by stormpython** [comment]
@ThorstenBux do you not see the plugin showing up as a new visualization type within the visualization tab? It should be step 1 of the process.

I'll need to check to see if any changes were pushed that affects the plugin. But a screen shot of the visualize tab would help.

Thanks.

**Comment by ThorstenBux** [comment]
@stormpython : I'm sorry it is right there. Somehow I overlooked it or it needed a restart to show up.

I close this now.
